// <auto-generated />
namespace IShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _3sep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3sep));
        
        string IMigrationMetadata.Id
        {
            get { return "202009030706591_3sep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
